### ISSUE TITLE
Angular 14 Support

### ISSUE THREAD

**Issue by sic-sic** [sinequa/ngx-ui-builder#67]
`ng add @sinequa/ngx-ui-builder` actually does not work with an angular 14 project and I don't want to downgrade to angular 12.
It would be possible to upgrade to angular 14 ?
I can contribute if you want.

**Comment by ericleib** [comment]
Hello,
What kind of error do you have? There probably isn't a big compatibility problem, but more likely a conflict with the peer dependency versions we listed in the package.json.
We'll have limited bandwidth to help you during early August, but we definitely welcome external contributions, and we will review Pull Requests 🙂
