### ISSUE TITLE
Schematics missing from latest npm package (0.2.4)

### ISSUE THREAD

**Issue by co-dax** [sinequa/ngx-ui-builder#95]
The latest npm package available for this project is 0.2.4 ([https://www.npmjs.com/package/@sinequa/ngx-ui-builder?activeTab=versions](https://www.npmjs.com/package/@sinequa/ngx-ui-builder?activeTab=versions)) so when we running the following command `ng generate ngx-ui-builder:make-static -- --config=my-config.json` to generate static templates as suggested at the following page in the docs [https://github.com/sinequa/ngx-ui-builder?tab=readme-ov-file#static-export](https://github.com/sinequa/ngx-ui-builder?tab=readme-ov-file#static-export) it results in the following exception `An unhandled exception occurred: Collection ".....\\ngx-ui-builder\\node_modules\\@sinequa\\ngx-ui-builder\\schematics\\collection.json" cannot be resolved.` which is due to not having published the latest project version (1.0.0) on npm. The latest version on npm (0.2.4) is missing `schematics` folder containg `collection.json` file mentioned in the error I reported above in the text.
![image](https://github.com/sinequa/ngx-ui-builder/assets/7594292/4a777ff0-ae07-49ab-be8a-dd12a2abf8c4)

...but it works fine if I build the library locally, copy the build artifacts to the `node_modules\@sinequa\ngx-ui-builder` and then run `ng generate ngx-ui-builder:make-static -- --config=my-config.json` again since now there is `schematics` folder with `collection.json` file in library build output folder:

![image](https://github.com/sinequa/ngx-ui-builder/assets/7594292/335d1326-19dc-4e09-a659-d42ad63b51bc)

I would say the latest project version should be deployed to npm.

Thanks.

**Comment by co-dax** [comment]
By the way, I am interested in contributing to this project.

**Comment by hebus** [comment]
npm package updated to 1.0.0

**Comment by co-dax** [comment]
Thanks @hebus
