### ISSUE TITLE
"Download" button for exporting configuration missing

### ISSUE THREAD

**Issue by co-dax** [sinequa/ngx-ui-builder#96]
"Download" button for exporting configuration is missing:

![image](https://github.com/sinequa/ngx-ui-builder/assets/7594292/c44885cf-a9ff-431b-97b0-0cc19c229ddc)
[https://sinequa.github.io/ngx-ui-builder/demo/](https://sinequa.github.io/ngx-ui-builder/demo/)

The following changes is working
![image](https://github.com/sinequa/ngx-ui-builder/assets/7594292/9bfed390-7b0e-4526-8592-4acd55851767)

![image](https://github.com/sinequa/ngx-ui-builder/assets/7594292/e0501b1f-ce70-42c5-b23a-6803c7193a26)

If this is ok then the following line should be redundant:

![image](https://github.com/sinequa/ngx-ui-builder/assets/7594292/a7841277-5e3b-455f-b845-a69c5e759cd9)

**Comment by hebus** [comment]
Thanks, correction done
